name: "Cachix"
on:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            extra-substituters = https://nixpkgs-unfree.cachix.org
      - uses: cachix/cachix-action@v10
        with:
          name: goatpkgs
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build .#devShell.x86_64-linux
